// <auto-generated />
using DeadLinerWebApp.DAL.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeadLinerWebApp.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210421092133_DeleteInvites")]
    partial class DeleteInvites
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Hub", b =>
                {
                    b.Property<int>("HubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HubId");

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            HubId = 1,
                            Code = "testCodeHub1",
                            Description = "testHubDescription1",
                            Name = "testNameHub1"
                        },
                        new
                        {
                            HubId = 2,
                            Code = "testCodeHub2",
                            Description = "testHubDescription2",
                            Name = "testNameHub2"
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.RecoveryCode", b =>
                {
                    b.Property<int>("RecoveryCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecoveryCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("RecoveryCodes");

                    b.HasData(
                        new
                        {
                            RecoveryCodeId = 1,
                            Code = "test",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Title = "mentee"
                        },
                        new
                        {
                            RoleId = 2,
                            Title = "mentor"
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("HubId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Description = "Make a good visual concept",
                            HubId = 1,
                            Name = "TODO Index page",
                            Resources = "https://www.w3schools.com"
                        },
                        new
                        {
                            TaskId = 2,
                            Description = "Make a good visual concept",
                            HubId = 1,
                            Name = "TODO Home page",
                            Resources = "https://www.w3schools.com"
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "testEmail@lnu.edu.ua",
                            FullName = "TestFullName1",
                            Password = "test"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Serhii.Yurko@lnu.edu.ua",
                            FullName = "Serhii Yurko",
                            Password = "serhii"
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.UsersHubs", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("HubId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersHubsId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "HubId");

                    b.HasIndex("HubId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersHubs");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            HubId = 1,
                            RoleId = 1,
                            TeamName = "testTeam1",
                            UsersHubsId = 1
                        },
                        new
                        {
                            UserId = 2,
                            HubId = 1,
                            RoleId = 1,
                            TeamName = "testTeam1",
                            UsersHubsId = 2
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.UsersTasks", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsersTasksId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TaskId", "TaskStatus");

                    b.HasIndex("TaskId");

                    b.ToTable("UsersTasks");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            TaskId = 1,
                            TaskStatus = "New",
                            UsersTasksId = 1
                        },
                        new
                        {
                            UserId = 1,
                            TaskId = 2,
                            TaskStatus = "InProgress",
                            UsersTasksId = 1
                        });
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.RecoveryCode", b =>
                {
                    b.HasOne("DeadLinerWebApp.DAL.Entity.User", "User")
                        .WithMany("Code")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Task", b =>
                {
                    b.HasOne("DeadLinerWebApp.DAL.Entity.Hub", "Hub")
                        .WithMany("Tasks")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.UsersHubs", b =>
                {
                    b.HasOne("DeadLinerWebApp.DAL.Entity.Hub", "Hub")
                        .WithMany("UsersHubs")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadLinerWebApp.DAL.Entity.Role", "Role")
                        .WithMany("UsersHubs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadLinerWebApp.DAL.Entity.User", "User")
                        .WithMany("UsersHubs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.UsersTasks", b =>
                {
                    b.HasOne("DeadLinerWebApp.DAL.Entity.Task", "Task")
                        .WithMany("UsersTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadLinerWebApp.DAL.Entity.User", "User")
                        .WithMany("UsersTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Hub", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("UsersHubs");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Role", b =>
                {
                    b.Navigation("UsersHubs");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.Task", b =>
                {
                    b.Navigation("UsersTasks");
                });

            modelBuilder.Entity("DeadLinerWebApp.DAL.Entity.User", b =>
                {
                    b.Navigation("Code");

                    b.Navigation("UsersHubs");

                    b.Navigation("UsersTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
